name: Check Package Updates

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.matrix.outputs.GITHUB_OUTPUT }}
    steps:
      - uses: actions/checkout@v4
      - id: matrix
        run: cat packages.json >> "GITHUB_OUTPUT"

  check-updates:
    needs: setup-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{fromJson(needs.setup-matrix.outputs.packages)}}
    steps:
      - run: echo ${{ matrix.package }}
