name: Rebase Packages

on:
  pull_request:
    paths:
      - "packages-rebase.json"
      - ".github/workflows/rebase-packages.yaml"
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.matrix.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - id: matrix
        run: |
          {
            echo 'packages<<EOF'
            jq -rc .packages packages-rebase.json
            echo 'EOF'
          } >> "${GITHUB_OUTPUT}"

  rebase-with-node-packages-generate:
    needs: setup-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.packages).withNodePackagesGenerate }}
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          repositories: nixpkgs
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: wattmto/nixpkgs
          ref: 'master'
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@v11
        with:
          extra-conf: |
            trusted-substituters = https://cache.nixos.org/ https://nix-community.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
            sandbox = true
      - uses: DeterminateSystems/magic-nix-cache-action@v6
      - name: Create branch
        run: git checkout -b ${{ matrix.package }}
      - name: Configure git
        run: |
          git config user.email "93639059+wattmto@users.noreply.github.com"
          git config user.name "wattmto"
      - name: Checkout
        run: git checkout ${{ matrix.package }}
      - name: Rebase
        run: git rebase -X theirs origin/master
      - name: Generate node-packages.nix
        run: ./pkgs/development/node-packages/generate.sh
      - name: Commit changes
        run: |
          git add pkgs/development/node-packages/node-packages.nix
          git commit --amend --no-edit
      - name: Push changes
        run: |
          git push -f origin ${{ matrix.package }}:rebase-${{ matrix.package }}
